begin;

-- Bootstrap for a FRESH database (e.g. self-hosted / local Supabase).
--
-- Migration 001 ALTERs tables that the main Schowl web app normally creates
-- (courses, teacher, lesson, client, teacher_course, password_reset_tokens).
-- On a database that already has them (the cloud project) you SKIP this file.
-- On a fresh database, run THIS FIRST — it creates those base tables in their
-- pre-SchowlBot form, then 001..012 add the SchowlBot columns/tables on top.

create extension if not exists "uuid-ossp";
create extension if not exists pgcrypto;

create table if not exists public.courses (
  id uuid primary key default uuid_generate_v4(),
  name_en text,
  name_ar text,
  description jsonb not null default '{"ar": "", "en": ""}'::jsonb,
  stages jsonb not null default '{"ar": [], "en": []}'::jsonb,
  "stageText" jsonb not null default '{"ar": "", "en": ""}'::jsonb,
  tracks jsonb not null default '{"ar": [], "en": []}'::jsonb,
  min_age integer,
  max_age integer,
  icon text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.client (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text,
  parent_name text,
  email text,
  age smallint,
  gov text,
  phone bigint,
  phone_alt bigint,
  course text,
  plan text,
  country text,
  interests text[]
);

create table if not exists public.teacher (
  id uuid primary key,
  name text,
  email text,
  phone_number text,
  age integer,
  total_lessons integer,
  created_at timestamptz default now()
);

create table if not exists public.lesson (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  client_id bigint references public.client(id),
  teacher_id uuid references public.teacher(id),
  course_id bigint,
  date timestamp,
  status text not null default 'Pending',
  lesson integer default 0
);

create table if not exists public.teacher_course (
  id bigint generated by default as identity primary key,
  teacher_id uuid references public.teacher(id),
  course_id bigint,
  created_at timestamptz not null default now()
);

create table if not exists public.password_reset_tokens (
  id integer generated by default as identity primary key,
  user_id uuid,
  token text not null,
  used boolean default false,
  created_at timestamptz default now()
);

commit;
